### ISSUE TITLE
Memory exhausted on JsonBuilder.php on line 131

### ISSUE THREAD

**Issue by abkrim** [egeloen/ivory-json-builder#3] opened 2015-08-29 09:13 UTC
Hello

I caught an exception while trying to pass an array.
````memory_limit = 256M````
````
Allowed memory size of 268435456 bytes exhausted (tried to allocate 137 bytes) in /usr/local/cpanel/whostmgr/docroot/cgi/cprsync/vendor/egeloen/json-builder/src/JsonBuilder.php on line 131
````
````
$json = self::listFoldersToJson(InitApp::$cfg['user_home']);
                // Guardmos con la la clase json
                $builder = new JsonBuilder();
                //->setJsonEncodeOptions(JSON_FORCE_OBJECT)
                $json_encode = $builder
                    ->reset()
                    ->setValues($json)
                    ->build();
````
$json it's array with 

````
 $info = array(
                'file'        => $fs_info->getFilename(),
                'path'        => str_replace(InitApp::$cfg['user_home'].'/','',str_replace('\\', '/',$fs_info->getPathname())),
                'permissions' => substr(sprintf('%o', $fs_info->getPerms()), -4),
                'owner'       => $fs_info->getOwner(),
                'group'       => $fs_info->getGroup(),
                'size'        => $fs_info->getSize (),
                'date'        => $fs_info->getMTime(),
                'depth'       => $depth
            );
...
Apreciate help...
````

**Comment by egeloen** [comment] 2015-12-06 14:10
Sorry for the very late answer... I just give a try to your issue by reproducing it with a very large and deep array but I can't get a memory exhaust... Not sure what is causing it. Can you copy/paste the `json` var content instead of its structure?

**Comment by egeloen** [comment] 2015-12-30 16:11
I will close it as indeed the library will duplicate the amount of memory used by a factor nearest of 2 but  this is a know limitation I'm not sure I will be able to remove it. The point is the builder is statefull (keeping a copy of your values internally) and then, there is no way to remove that since it is a builder...

Anyway, if someone else dig into this issue, giving me a reproductibe use case would be great in order to let me investigate it.

**Closed by egeloen** 2015-12-30 16:11 UTC
